export const DEFAULT_CATEGORIES = [
    { name: "Alimentação", color: "#f97316", is_personal: true },
    { name: "Assinaturas e serviços", color: "#64748b", is_personal: true },
    { name: "Bares e restaurantes", color: "#ef4444", is_personal: true },
    { name: "Casa", color: "#3b82f6", is_personal: true },
    { name: "Compras", color: "#ec4899", is_personal: true },
    { name: "Cuidados pessoais", color: "#06b6d4", is_personal: true },
    { name: "Dívidas e empréstimos", color: "#71717a", is_personal: true },
    { name: "Educação", color: "#8b5cf6", is_personal: true },
    { name: "Família e filhos", color: "#a855f7", is_personal: true },
    { name: "Impostos e Taxas", color: "#fb7185", is_personal: true },
    { name: "Investimentos", color: "#10b981", is_personal: true },
    { name: "Lazer e hobbies", color: "#f59e0b", is_personal: true },
    { name: "Mercado", color: "#d946ef", is_personal: true },
    { name: "Outros", color: "#9ca3af", is_personal: true },
    { name: "Pets", color: "#14b8a6", is_personal: true },
    { name: "Presentes e doações", color: "#f43f5e", is_personal: true },
    { name: "Roupas", color: "#3b82f6", is_personal: true },
    { name: "Saúde", color: "#22c55e", is_personal: true },
    { name: "Trabalho", color: "#6366f1", is_personal: true },
    { name: "Transporte", color: "#0ea5e9", is_personal: true },
    { name: "Viagem", color: "#eab308", is_personal: true },
]
